### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'UE' when running the run-synthesizers.py

### ISSUE THREAD

**Issue by thusithathilina** [SyNSec-den/hermes-spec-to-fsm#4]
I'm getting following error when running the run-synthesizers.py
```
Line 829 : <root> UE AMF AUTHENTICATION REQUEST Start T3560 & lt; EAP-request message A &gt; AUTHENTICATION RESPONSE </root>
Traceback (most recent call last):
  File "./run-synthesizers.py", line 457, in <module>
    section_info = call_update_header_context(line[6:-7].strip())
  File "/fs03/cn99/tday0004/hermes-spec-to-fsm/synthesizers/script_dep2ir.py", line 63, in call_update_header_context
    return update_header_context(text)
  File "/fs03/cn99/tday0004/hermes-spec-to-fsm/synthesizers/script_context.py", line 132, in update_header_context
    is_header, header_name, header_type, header_level, header_text = isHeader(text)
  File "/fs03/cn99/tday0004/hermes-spec-to-fsm/synthesizers/script_helpers.py", line 243, in isHeader
    header_level = 200 + int(header_name)
ValueError: invalid literal for int() with base 10: 'UE'
```

**Comment by ishtiaqniloy** [comment]
Issue solved in the following commit:
d37fe752fec2592dcc10cc11fabfcb6429d6a216
